CREATE TABLE SINGER (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , GENRE VARCHAR(60)
     , BIRTH_DATE DATE
     , PRIMARY KEY (ID)
);
