server:
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/webdb?useSSL=false
    username: prospring6
    password: prospring6
    hikari:
      maximum-pool-size: 10
