INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (1, 0, 'Ben', 'Barnes', '1946-09-05');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (2, 0, 'David', 'Bowie', '1947-01-08');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (3, 0, 'Elton', 'John', '1947-03-25');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (4, 0, 'Stevie', 'Nicks', '1948-05-26');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (5, 0, 'Robert', 'Plant', '1948-08-20');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (6, 0, 'Freddy', 'Fender', '1937-06-04');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (7, 0, 'Anni-Frid', 'Lyngstad', '1945-11-15');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (8, 0, 'Agnetha', 'Faltskog', '1950-04-05');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (9, 0, 'Bjorn', 'Ulvaeus', '1945-04-25');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (10, 0, 'Benny', 'Andersson', '1946-12-16');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (11, 0, 'Bruce', 'Dickinson', '1958-08-07');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (12, 0, 'Ozzy', 'Osbourne', '1948-12-03');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (13, 0, 'Ronnie', 'Dio', '1942-07-10');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (14, 0, 'Rob', 'Halford', '1951-08-25');
INSERT INTO SINGER (ID, VERSION, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (15, 0, 'Bruce', 'Springsteen', '1949-09-23');

ALTER TABLE SINGER ALTER COLUMN ID RESTART WITH 16;
