plugins {
    id 'war'
}

description 'Chapter 18'

group = 'com.apress.prospring6'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.security:spring-security-config:6.0.3'
    implementation 'org.springframework.security:spring-security-web:6.0.3'
    implementation 'org.springframework:spring-webmvc:6.0.9'
    implementation 'org.thymeleaf:thymeleaf-spring6:3.1.1.RELEASE'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.1.RELEASE'
    implementation 'org.springframework.data:spring-data-jpa:3.0.6'
    implementation 'commons-io:commons-io:2.11.0'
    implementation 'org.glassfish:jakarta.el:5.0.0-M1'
    implementation 'org.hibernate.validator:hibernate-validator:8.0.0.Final'
    implementation 'org.hibernate.orm:hibernate-core:6.1.7.Final'
    implementation 'com.zaxxer:HikariCP:5.0.1'

    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client:3.0.10'

    implementation 'ch.qos.logback:logback-classic:1.4.5'
    implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'

    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    implementation 'org.apache.commons:commons-lang3:3.12.0'

    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.9.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework:spring-test:6.0.9'
    testImplementation 'io.rest-assured:rest-assured:5.3.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
