CREATE TABLE SINGER (
    ID INT NOT NULL AUTO_INCREMENT,
    VERSION INT NOT NULL DEFAULT 0,
    FIRST_NAME VARCHAR(60) NOT NULL,
    LAST_NAME VARCHAR(40) NOT NULL,
    BIRTH_DATE DATE,
    PHOTO LONGBLOB NULL,
    UNIQUE (FIRST_NAME, LAST_NAME),
    PRIMARY KEY (ID)
);

CREATE TABLE ALBUM (
    ID INT NOT NULL AUTO_INCREMENT,
    VERSION INT NOT NULL DEFAULT 0,
    TITLE VARCHAR(100) NOT NULL,
    RELEASE_DATE DATE,
    SINGER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SINGER_ID) REFERENCES SINGER (ID)
);
