CREATE TABLE SINGER (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , PSEUDONYM VARCHAR(60)
     , GENRE VARCHAR(60)
     , BIRTH_DATE DATE
     , PRIMARY KEY (ID)
);

CREATE TABLE INSTRUMENT (
       INSTRUMENT_ID VARCHAR(40) NOT NULL
     , PRIMARY KEY (INSTRUMENT_ID)
);

CREATE TABLE SINGER_INSTRUMENT (
       SINGER_ID INT NOT NULL
     , INSTRUMENT_ID VARCHAR(40) NOT NULL
     , PRIMARY KEY (SINGER_ID, INSTRUMENT_ID)
     , CONSTRAINT FK_SINGER_INSTRUMENT_SINGER FOREIGN KEY (SINGER_ID)
                  REFERENCES SINGER (ID)
     , CONSTRAINT FK_SINGER_INSTRUMENT_INSTRUMENT FOREIGN KEY (INSTRUMENT_ID)
                  REFERENCES INSTRUMENT (INSTRUMENT_ID)
);

CREATE TABLE AWARD (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , SINGER_ID INT NOT NULL
     , `YEAR` INT
     , TYPE VARCHAR(60)
     , ITEM_NAME VARCHAR(100)
     , AWARD_NAME VARCHAR(100)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_AWARD_SINGER FOREIGN KEY (SINGER_ID)
                  REFERENCES SINGER (ID)
);
